### PR TITLE
downcase a tag only when it is in the same case (useful for some came…

### PR DESCRIPTION
**Pull request by mgi**
…l case XML tags).

The interface might not be good but I have use case for this for some XML tags that are camel case (see https://www.w3schools.com/XML/schema_schema.asp).

With this patch, I can have every tag downcased while preserving camel case using, for instance, `:|xsi:schemaLocation|` keywords

### CODE REVIEW

**Comment by stassats** [comment]
It's probably better to factor that out into a maybe-downcase function.

**Comment by mgi** [comment]
Stas Boukarev <notifications@github.com> writes:

> It's probably better to factor that out into a maybe-downcase
> function.

Do you mean having *downcase-tokens-p* being 3 states (nil, t and
:maybe-downcase) or having a new interface variable like
*maybe-downcase-p*?
-- 
Manuel Giraud

**Comment by stassats** [comment]
No, a function function.

**Comment by mgi** [comment]
Stas Boukarev <notifications@github.com> writes:

> No, a function function.

Ok. I think my last patch does this.
-- 
Manuel Giraud

**Comment by mgi** [comment]
Stas Boukarev <notifications@github.com> writes:

> Merged #29 into master.

Thanks.
-- 
Manuel Giraud

**Pull request merged**
